import { ApiProperty } from '@nestjs/swagger';
import {
  IsEmail,
  IsNotEmpty,
  IsString,
  MinLength,
  Matches,
} from 'class-validator';

export class AccountReqDto {
  @ApiProperty({
    example: 'user@example.com',
    description: 'User email address for registration',
  })
  @IsEmail()
  @IsNotEmpty()
  email: string;

  @ApiProperty({
    example: 'passw0rD1234',
    description:
      'User password (minimum 8 characters, must contain letters and numbers)',
    minLength: 8,
  })
  @IsString()
  @IsNotEmpty()
  @MinLength(8)
  @Matches(/^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d@$!%*#?&]{8,}$/, {
    message: 'Password must contain at least one letter and one number',
  })
  password: string;

  @ApiProperty({
    example: 'ad633491-9eb8-4fb5-bc69-310953633c6c',
    description: 'Device Id (generated by the client application)',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;
}
